
server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://10.8.1.200:3306/appmanager?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: appmanager
    password: appmanager
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: @profiles.active@

#log
logging:
  level: debug

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.david.entity




