server:
  port: 8080
##数据库url
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf8&useSSL=false
    ##数据库用户名
    username: root

    ##数据库密码
    password: root
    ##数据库驱动
    driver-class-name: com.mysql.jdbc.Driver

#log
logging:
  level: debug

##mybatis-plus mapper xml 文件地址
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  ##mybatis-plus type-aliases 文件地址
  type-aliases-package: com.david.entity


