server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#log
logging:
  level: debug

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.david.entity


